CREATE TABLE [dbo].[BillPrintModel] (
    [Id]                 INT             IDENTITY (1, 1) NOT NULL,
    [GroupId]            INT             NOT NULL,
    [Title]              NVARCHAR (MAX)  NULL,
    [GSTN]               NVARCHAR (MAX)  NULL,
    [PAN]                NVARCHAR (MAX)  NULL,
    [InvoiceNo]          NVARCHAR (MAX)  NULL,
    [InvoiceDate]        DATETIME2 (7)   NOT NULL,
    [ReverseCharge]      NVARCHAR (MAX)  NULL,
    [State]              NVARCHAR (MAX)  NULL,
    [Code]               NVARCHAR (MAX)  NULL,
    [TCSApplicable]      NVARCHAR (MAX)  NULL,
    [DateOfSupply]       DATETIME2 (7)   NOT NULL,
    [PlaceOfSupply]      NVARCHAR (MAX)  NULL,
    [Terms]              NVARCHAR (MAX)  NULL,
    [BillPartyName]      NVARCHAR (MAX)  NULL,
    [BillPartyAddress]   NVARCHAR (MAX)  NULL,
    [BillPartyGSTIN]     NVARCHAR (MAX)  NULL,
    [BillPartyPAN]       NVARCHAR (MAX)  NULL,
    [BillPartyState]     NVARCHAR (MAX)  NULL,
    [BillPartyCode]      NVARCHAR (MAX)  NULL,
    [ShipPartyName]      NVARCHAR (MAX)  NULL,
    [ShipPartyAddress]   NVARCHAR (MAX)  NULL,
    [ShipPartyGSTIN]     NVARCHAR (MAX)  NULL,
    [ShipPartyPAN]       NVARCHAR (MAX)  NULL,
    [ShipPartyState]     NVARCHAR (MAX)  NULL,
    [ShipPartyCode]      NVARCHAR (MAX)  NULL,
    [AmountBeforeTax]    DECIMAL (18, 2) NOT NULL,
    [SGST]               DECIMAL (18, 2) NOT NULL,
    [CGST]               DECIMAL (18, 2) NOT NULL,
    [IGST]               DECIMAL (18, 2) NOT NULL,
    [TCS]                DECIMAL (18, 2) NOT NULL,
    [TotalAmount]        DECIMAL (18, 2) NOT NULL,
    [GstOnReverseCharge] DECIMAL (18, 2) NOT NULL,
    [Declaration]        NVARCHAR (MAX)  NULL,
    [BankName]           NVARCHAR (MAX)  NULL,
    [AccountNo]          NVARCHAR (MAX)  NULL,
    [IFSC]               NVARCHAR (MAX)  NULL,
    [SrNo]               NVARCHAR (MAX)  NULL,
    [ProductDescription] NVARCHAR (MAX)  NULL,
    [HSNCode]            NVARCHAR (MAX)  NULL,
    [UOM]                NVARCHAR (MAX)  NULL,
    [Qty]                DECIMAL (18, 2) NOT NULL,
    [Rate]               DECIMAL (18, 2) NOT NULL,
    [Amount]             DECIMAL (18, 2) NOT NULL,
    [Discount]           DECIMAL (18, 2) NOT NULL,
    [TaxableValue]       DECIMAL (18, 2) NOT NULL,
    [TotalRow]           DECIMAL (18, 2) NOT NULL,
    [TotalQty]           DECIMAL (18, 2) NOT NULL,
    [TotalGridAmount]    DECIMAL (18, 2) NOT NULL,
    [TotalTaxValue]      DECIMAL (18, 2) NOT NULL,
    [FinalTotal]         DECIMAL (18, 2) NOT NULL,
    [BranchId]           NVARCHAR (MAX)  NULL,
    [CompanyId]          NVARCHAR (MAX)  NULL,
    [FinancialYearId]    NVARCHAR (MAX)  NULL,
    [AmountInWords]      NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_BillPrintModel] PRIMARY KEY CLUSTERED ([Id] ASC)
);

