CREATE TABLE [dbo].[BoilProcessMaster] (
    [Id]                       NVARCHAR (450)  NOT NULL,
    [Sr]                       INT             IDENTITY (1, 1) NOT NULL,
    [BoilNo]                   INT             NOT NULL,
    [PurchaseDetailsId]        NVARCHAR (MAX)  NULL,
    [JangadNo]                 INT             NOT NULL,
    [CompanyId]                NVARCHAR (MAX)  NULL,
    [BranchId]                 NVARCHAR (MAX)  NULL,
    [EntryDate]                NVARCHAR (MAX)  NULL,
    [EntryTime]                NVARCHAR (MAX)  NULL,
    [FinancialYearId]          NVARCHAR (MAX)  NULL,
    [BoilType]                 INT             NOT NULL,
    [KapanId]                  NVARCHAR (MAX)  NULL,
    [ShapeId]                  NVARCHAR (MAX)  NULL,
    [SizeId]                   NVARCHAR (MAX)  NULL,
    [PurityId]                 NVARCHAR (MAX)  NULL,
    [Weight]                   DECIMAL (18, 4) NOT NULL,
    [LossWeight]               DECIMAL (18, 4) NOT NULL,
    [RejectionWeight]          DECIMAL (18, 4) NOT NULL,
    [HandOverById]             NVARCHAR (MAX)  NULL,
    [HandOverToId]             NVARCHAR (MAX)  NULL,
    [SlipNo]                   NVARCHAR (MAX)  NULL,
    [BoilCategoy]              INT             NOT NULL,
    [Remarks]                  NVARCHAR (MAX)  NULL,
    [TransferId]               NVARCHAR (MAX)  NULL,
    [TransferType]             NVARCHAR (MAX)  NULL,
    [TransferEntryId]          NVARCHAR (MAX)  NULL,
    [TransferCaratRate]        FLOAT (53)      NOT NULL,
    [IsDelete]                 BIT             NOT NULL,
    [CreatedDate]              DATETIME2 (7)   NOT NULL,
    [UpdatedDate]              DATETIME2 (7)   NULL,
    [CreatedBy]                NVARCHAR (MAX)  NULL,
    [UpdatedBy]                NVARCHAR (MAX)  NULL,
    [StockId]                  NVARCHAR (MAX)  NULL,
    [AccountToAssortDetailsId] NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_BoilProcessMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

