CREATE TABLE [dbo].[NumberProcessMaster] (
    [Id]                NVARCHAR (450)  NOT NULL,
    [Sr]                INT             IDENTITY (1, 1) NOT NULL,
    [NumberNo]          INT             NOT NULL,
    [JangadNo]          INT             NOT NULL,
    [CompanyId]         NVARCHAR (MAX)  NULL,
    [BranchId]          NVARCHAR (MAX)  NULL,
    [EntryDate]         NVARCHAR (MAX)  NULL,
    [EntryTime]         NVARCHAR (MAX)  NULL,
    [FinancialYearId]   NVARCHAR (MAX)  NULL,
    [NumberProcessType] INT             NOT NULL,
    [KapanId]           NVARCHAR (MAX)  NULL,
    [ShapeId]           NVARCHAR (MAX)  NULL,
    [SizeId]            NVARCHAR (MAX)  NULL,
    [PurityId]          NVARCHAR (MAX)  NULL,
    [Weight]            DECIMAL (18, 4) NOT NULL,
    [GalaNumberId]      NVARCHAR (MAX)  NULL,
    [NumberId]          NVARCHAR (MAX)  NULL,
    [NumberWeight]      DECIMAL (18, 4) NOT NULL,
    [LossWeight]        DECIMAL (18, 4) NOT NULL,
    [RejectionWeight]   DECIMAL (18, 4) NOT NULL,
    [HandOverById]      NVARCHAR (MAX)  NULL,
    [HandOverToId]      NVARCHAR (MAX)  NULL,
    [SlipNo]            NVARCHAR (MAX)  NULL,
    [NumberCategoy]     INT             NOT NULL,
    [Remarks]           NVARCHAR (MAX)  NULL,
    [TransferId]        NVARCHAR (MAX)  NULL,
    [TransferType]      NVARCHAR (MAX)  NULL,
    [TransferEntryId]   NVARCHAR (MAX)  NULL,
    [TransferCaratRate] FLOAT (53)      NOT NULL,
    [IsDelete]          BIT             NOT NULL,
    [CreatedDate]       DATETIME2 (7)   NOT NULL,
    [UpdatedDate]       DATETIME2 (7)   NULL,
    [CreatedBy]         NVARCHAR (MAX)  NULL,
    [UpdatedBy]         NVARCHAR (MAX)  NULL,
    [CharniSizeId]      NVARCHAR (MAX)  NULL,
    [PurchaseDetailsId] NVARCHAR (MAX)  NULL,
    [PurchaseMasterId]  NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_NumberProcessMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

