CREATE TABLE [dbo].[OpeningStockMaster] (
    [Id]                NVARCHAR (450)  NOT NULL,
    [Sr]                INT             IDENTITY (1, 1) NOT NULL,
    [SrNo]              INT             NOT NULL,
    [CompanyId]         NVARCHAR (MAX)  NULL,
    [BranchId]          NVARCHAR (MAX)  NULL,
    [FinancialYearId]   NVARCHAR (MAX)  NULL,
    [KapanId]           NVARCHAR (MAX)  NULL,
    [ShapeId]           NVARCHAR (MAX)  NULL,
    [SizeId]            NVARCHAR (MAX)  NULL,
    [PurityId]          NVARCHAR (MAX)  NULL,
    [TotalCts]          DECIMAL (18, 4) NOT NULL,
    [Rate]              DECIMAL (18, 4) NOT NULL,
    [Amount]            DECIMAL (18, 4) NOT NULL,
    [CreatedDate]       DATETIME2 (7)   NOT NULL,
    [UpdatedDate]       DATETIME2 (7)   NULL,
    [CreatedBy]         NVARCHAR (MAX)  NULL,
    [UpdatedBy]         NVARCHAR (MAX)  NULL,
    [NumberId]          NVARCHAR (MAX)  NULL,
    [Category]          INT             DEFAULT ((0)) NOT NULL,
    [EntryDate]         NVARCHAR (MAX)  NULL,
    [EntryTime]         NVARCHAR (MAX)  NULL,
    [Remarks]           NVARCHAR (MAX)  NULL,
    [TransferId]        NVARCHAR (MAX)  NULL,
    [TransferCaratRate] FLOAT (53)      DEFAULT ((0.0000000000000000e+000)) NOT NULL,
    [TransferEntryId]   NVARCHAR (MAX)  NULL,
    [TransferType]      NVARCHAR (MAX)  NULL,
    [StockId]           NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_OpeningStockMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

