CREATE TABLE [dbo].[PartyMaster] (
    [Id]             NVARCHAR (450)  NOT NULL,
    [Sr]             INT             IDENTITY (1, 1) NOT NULL,
    [CompanyId]      NVARCHAR (450)  NULL,
    [BrokerageId]    NVARCHAR (MAX)  NULL,
    [Type]           INT             NOT NULL,
    [SubType]        INT             NOT NULL,
    [Name]           NVARCHAR (MAX)  NULL,
    [ShortName]      NVARCHAR (MAX)  NULL,
    [EmailId]        NVARCHAR (MAX)  NULL,
    [Address]        NVARCHAR (MAX)  NULL,
    [Address2]       NVARCHAR (MAX)  NULL,
    [MobileNo]       NVARCHAR (MAX)  NULL,
    [OfficeNo]       NVARCHAR (MAX)  NULL,
    [GSTNo]          NVARCHAR (MAX)  NULL,
    [AadharCardNo]   NVARCHAR (MAX)  NULL,
    [PancardNo]      NVARCHAR (MAX)  NULL,
    [OpeningBalance] DECIMAL (18, 4) NOT NULL,
    [IsDelete]       BIT             NOT NULL,
    [Status]         BIT             NOT NULL,
    [CreatedDate]    DATETIME2 (7)   NOT NULL,
    [UpdatedDate]    DATETIME2 (7)   NULL,
    [CreatedBy]      NVARCHAR (MAX)  NULL,
    [UpdatedBy]      NVARCHAR (MAX)  NULL,
    [Salary]         DECIMAL (18, 4) DEFAULT ((0.0)) NOT NULL,
    [CRDRType]       INT             DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PartyMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PartyMaster_CompanyMaster_CompanyId] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[CompanyMaster] ([Id])
);

