CREATE TABLE [dbo].[RejectionInOutMaster] (
    [Id]                    NVARCHAR (450)  NOT NULL,
    [Sr]                    INT             IDENTITY (1, 1) NOT NULL,
    [SrNo]                  INT             NOT NULL,
    [CompanyId]             NVARCHAR (MAX)  NULL,
    [BranchId]              NVARCHAR (MAX)  NULL,
    [EntryDate]             NVARCHAR (MAX)  NULL,
    [PartyId]               NVARCHAR (MAX)  NULL,
    [BrokerageId]           NVARCHAR (MAX)  NULL,
    [FinancialYearId]       NVARCHAR (MAX)  NULL,
    [TransType]             INT             NOT NULL,
    [SlipNo]                NVARCHAR (MAX)  NULL,
    [SizeId]                NVARCHAR (MAX)  NULL,
    [Rate]                  DECIMAL (18, 4) NOT NULL,
    [TotalCarat]            DECIMAL (18, 4) NOT NULL,
    [Amount]                DECIMAL (18, 4) NOT NULL,
    [Image1]                VARBINARY (MAX) NULL,
    [Image2]                VARBINARY (MAX) NULL,
    [Image3]                VARBINARY (MAX) NULL,
    [Remarks]               NVARCHAR (MAX)  NULL,
    [CreatedDate]           DATETIME2 (7)   NOT NULL,
    [UpdatedDate]           DATETIME2 (7)   NULL,
    [CreatedBy]             NVARCHAR (MAX)  NULL,
    [UpdatedBy]             NVARCHAR (MAX)  NULL,
    [CharniSizeId]          NVARCHAR (MAX)  NULL,
    [GalaSizeId]            NVARCHAR (MAX)  NULL,
    [NumberSizeId]          NVARCHAR (MAX)  NULL,
    [PurityId]              NVARCHAR (MAX)  NULL,
    [TableEntryID]          NVARCHAR (MAX)  NULL,
    [TableName]             NVARCHAR (MAX)  NULL,
    [ProcessType]           NVARCHAR (MAX)  NULL,
    [KapanId]               NVARCHAR (MAX)  NULL,
    [LessWeight]            DECIMAL (18, 4) DEFAULT ((0.0)) NOT NULL,
    [PurchaseSaleDetailsId] NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_RejectionInOutMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

