CREATE TABLE [dbo].[SalesDetailsSummary] (
    [Id]                NVARCHAR (450)  NOT NULL,
    [Sr]                INT             IDENTITY (1, 1) NOT NULL,
    [SalesId]           NVARCHAR (MAX)  NULL,
    [SalesDetailsId]    NVARCHAR (450)  NULL,
    [CompanyId]         NVARCHAR (MAX)  NULL,
    [BranchId]          NVARCHAR (MAX)  NULL,
    [FinancialYearId]   NVARCHAR (MAX)  NULL,
    [SlipNo]            NVARCHAR (MAX)  NULL,
    [KapanId]           NVARCHAR (MAX)  NULL,
    [ShapeId]           NVARCHAR (MAX)  NULL,
    [SizeId]            NVARCHAR (MAX)  NULL,
    [PurityId]          NVARCHAR (MAX)  NULL,
    [CharniSizeId]      NVARCHAR (MAX)  NULL,
    [GalaSizeId]        NVARCHAR (MAX)  NULL,
    [NumberSizeId]      NVARCHAR (MAX)  NULL,
    [Weight]            DECIMAL (18, 4) NOT NULL,
    [Category]          INT             NOT NULL,
    [PurchaseId]        NVARCHAR (MAX)  NULL,
    [PurchaseDetailsId] NVARCHAR (MAX)  NULL,
    [CreatedDate]       DATETIME2 (7)   NOT NULL,
    [UpdatedDate]       DATETIME2 (7)   NULL,
    [CreatedBy]         NVARCHAR (MAX)  NULL,
    [UpdatedBy]         NVARCHAR (MAX)  NULL,
    [StockId]           NVARCHAR (MAX)  NULL,
    [KapanType]         NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_SalesDetailsSummary] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_SalesDetailsSummary_SalesDetails_SalesDetailsId] FOREIGN KEY ([SalesDetailsId]) REFERENCES [dbo].[SalesDetails] ([Id])
);

