CREATE TABLE [dbo].[SPPartyMaster] (
    [Id]             NVARCHAR (450)  NOT NULL,
    [CompanyId]      NVARCHAR (MAX)  NULL,
    [BrokerageId]    NVARCHAR (MAX)  NULL,
    [Type]           INT             NOT NULL,
    [SubType]        INT             NOT NULL,
    [Name]           NVARCHAR (MAX)  NULL,
    [ShortName]      NVARCHAR (MAX)  NULL,
    [EmailId]        NVARCHAR (MAX)  NULL,
    [Address]        NVARCHAR (MAX)  NULL,
    [Address2]       NVARCHAR (MAX)  NULL,
    [MobileNo]       NVARCHAR (MAX)  NULL,
    [OfficeNo]       NVARCHAR (MAX)  NULL,
    [GSTNo]          NVARCHAR (MAX)  NULL,
    [AadharCardNo]   NVARCHAR (MAX)  NULL,
    [PancardNo]      NVARCHAR (MAX)  NULL,
    [Salary]         DECIMAL (18, 4) NOT NULL,
    [OpeningBalance] DECIMAL (18, 4) NOT NULL,
    [IsDelete]       BIT             NOT NULL,
    [Status]         BIT             NOT NULL,
    [CreatedDate]    DATETIME2 (7)   NOT NULL,
    [UpdatedDate]    DATETIME2 (7)   NULL,
    [CreatedBy]      NVARCHAR (MAX)  NULL,
    [UpdatedBy]      NVARCHAR (MAX)  NULL,
    [CRDRType]       INT             NOT NULL,
    [TypeName]       NVARCHAR (MAX)  NULL,
    [SubTypeName]    NVARCHAR (MAX)  NULL,
    [Balance]        DECIMAL (18, 4) NOT NULL,
    CONSTRAINT [PK_SPPartyMaster] PRIMARY KEY CLUSTERED ([Id] ASC)
);

