CREATE TABLE [dbo].[SPPurchaseChildReport] (
    [Id]                     NVARCHAR (MAX)  NULL,
    [PurchaseId]             NVARCHAR (MAX)  NULL,
    [KapanId]                NVARCHAR (MAX)  NULL,
    [ShapeId]                NVARCHAR (MAX)  NULL,
    [SizeId]                 NVARCHAR (MAX)  NULL,
    [PurityId]               NVARCHAR (MAX)  NULL,
    [Weight]                 DECIMAL (18, 4) NOT NULL,
    [TIPWeight]              DECIMAL (18, 4) NOT NULL,
    [CVDWeight]              DECIMAL (18, 4) NOT NULL,
    [RejectedPercentage]     DECIMAL (18, 4) NOT NULL,
    [RejectedWeight]         DECIMAL (18, 4) NOT NULL,
    [LessWeight]             DECIMAL (18, 4) NOT NULL,
    [LessDiscountPercentage] DECIMAL (18, 4) NOT NULL,
    [LessWeightDiscount]     DECIMAL (18, 4) NOT NULL,
    [NetWeight]              DECIMAL (18, 4) NOT NULL,
    [BuyingRate]             FLOAT (53)      NOT NULL,
    [CVDCharge]              FLOAT (53)      NOT NULL,
    [CVDAmount]              FLOAT (53)      NOT NULL,
    [Amount]                 FLOAT (53)      NOT NULL,
    [CurrencyRate]           DECIMAL (18, 4) NOT NULL,
    [CurrencyAmount]         DECIMAL (18, 4) NOT NULL,
    [IsTransfer]             BIT             NOT NULL,
    [TransferParentId]       NVARCHAR (MAX)  NULL,
    [CreatedDate]            DATETIME2 (7)   NOT NULL,
    [UpdatedDate]            DATETIME2 (7)   NULL,
    [CreatedBy]              NVARCHAR (MAX)  NULL,
    [UpdatedBy]              NVARCHAR (MAX)  NULL,
    [PurityName]             NVARCHAR (MAX)  NULL,
    [SizeName]               NVARCHAR (MAX)  NULL,
    [ShapeName]              NVARCHAR (MAX)  NULL
);

