CREATE TABLE [dbo].[SPRejectionSendReceiveReport] (
    [Id]              NVARCHAR (MAX)  NULL,
    [SrNo]            INT             NOT NULL,
    [CompanyId]       NVARCHAR (MAX)  NULL,
    [BranchId]        NVARCHAR (MAX)  NULL,
    [EntryDate]       DATETIME2 (7)   NULL,
    [PartyId]         NVARCHAR (MAX)  NULL,
    [PartyName]       NVARCHAR (MAX)  NULL,
    [BrokerageId]     NVARCHAR (MAX)  NULL,
    [BrokerName]      NVARCHAR (MAX)  NULL,
    [FinancialYearId] NVARCHAR (MAX)  NULL,
    [TransType]       INT             NOT NULL,
    [SlipNo]          NVARCHAR (MAX)  NULL,
    [SizeId]          NVARCHAR (MAX)  NULL,
    [SizeName]        NVARCHAR (MAX)  NULL,
    [PurityId]        NVARCHAR (MAX)  NULL,
    [PurityName]      NVARCHAR (MAX)  NULL,
    [CharniSizeId]    NVARCHAR (MAX)  NULL,
    [CharniSizeName]  NVARCHAR (MAX)  NULL,
    [GalaSizeId]      NVARCHAR (MAX)  NULL,
    [GalaSizeName]    NVARCHAR (MAX)  NULL,
    [NumberSizeId]    NVARCHAR (MAX)  NULL,
    [NumberSizeName]  NVARCHAR (MAX)  NULL,
    [Rate]            DECIMAL (18, 4) NOT NULL,
    [TotalCarat]      DECIMAL (18, 4) NOT NULL,
    [Amount]          DECIMAL (18, 4) NOT NULL,
    [Remarks]         NVARCHAR (MAX)  NULL
);

