CREATE TABLE [dbo].[SPSalaryReport] (
    [Id]                  NVARCHAR (MAX)  NULL,
    [SalaryMasterId]      NVARCHAR (MAX)  NULL,
    [Sr]                  INT             NOT NULL,
    [CompanyId]           NVARCHAR (MAX)  NULL,
    [BranchId]            NVARCHAR (MAX)  NULL,
    [FinancialYearId]     NVARCHAR (MAX)  NULL,
    [FromPartyId]         NVARCHAR (MAX)  NULL,
    [FromPartyName]       NVARCHAR (MAX)  NULL,
    [SalaryMonth]         INT             NOT NULL,
    [SalaryMonthDateTime] DATETIME2 (7)   NOT NULL,
    [MonthDays]           INT             NOT NULL,
    [Holidays]            REAL            NOT NULL,
    [Remarks]             NVARCHAR (MAX)  NULL,
    [ToPartyId]           NVARCHAR (MAX)  NULL,
    [ToPartyName]         NVARCHAR (MAX)  NULL,
    [SalaryAmount]        DECIMAL (18, 4) NOT NULL,
    [WorkingDays]         DECIMAL (18, 2) NOT NULL,
    [WorkedDays]          DECIMAL (18, 2) NOT NULL,
    [OTMinusRate]         DECIMAL (18, 2) NOT NULL,
    [OTPlusRate]          DECIMAL (18, 2) NOT NULL,
    [AdvanceAmount]       DECIMAL (18, 4) NOT NULL,
    [BonusAmount]         DECIMAL (18, 4) NOT NULL,
    [RoundOfAmount]       DECIMAL (18, 2) NOT NULL,
    [TotalAmount]         DECIMAL (18, 4) NOT NULL,
    [OTMinusHrs]          DECIMAL (18, 2) DEFAULT ((0.0)) NOT NULL,
    [OTPlusHrs]           DECIMAL (18, 4) DEFAULT ((0.0)) NOT NULL,
    [SrNo]                INT             DEFAULT ((0)) NOT NULL
);

