CREATE TABLE [dbo].[TransferViewModel] (
    [Id]                    NVARCHAR (450)  NOT NULL,
    [TransferMasterId]      NVARCHAR (MAX)  NULL,
    [JangadNo]              INT             NOT NULL,
    [Date]                  DATETIME2 (7)   NULL,
    [Time]                  NVARCHAR (MAX)  NULL,
    [TRansferById]          NVARCHAR (MAX)  NULL,
    [CompanyId]             NVARCHAR (MAX)  NULL,
    [CharniSizeId]          NVARCHAR (MAX)  NULL,
    [FromCategory]          INT             NOT NULL,
    [BranchId]              NVARCHAR (MAX)  NULL,
    [ShapeId]               NVARCHAR (MAX)  NULL,
    [Carat]                 DECIMAL (18, 2) NOT NULL,
    [Rate]                  DECIMAL (18, 4) NOT NULL,
    [Amount]                FLOAT (53)      NOT NULL,
    [ToCategory]            INT             NOT NULL,
    [ToSizeId]              NVARCHAR (MAX)  NULL,
    [ToBranchId]            NVARCHAR (MAX)  NULL,
    [ToNumberIdORKapanId]   NVARCHAR (MAX)  NULL,
    [ToCarat]               DECIMAL (18, 2) NOT NULL,
    [ToRate]                DECIMAL (18, 4) NOT NULL,
    [ToAmount]              FLOAT (53)      NOT NULL,
    [FromNumberIdORKapanId] NVARCHAR (MAX)  NULL,
    [Sr]                    INT             NOT NULL,
    [TrasnferDetailsSR]     INT             NOT NULL,
    [Name]                  NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_TransferViewModel] PRIMARY KEY CLUSTERED ([Id] ASC)
);

