CREATE TABLE [dbo].[UserMaster] (
    [Id]             NVARCHAR (450) NOT NULL,
    [Sr]             INT            IDENTITY (1, 1) NOT NULL,
    [UserCode]       NVARCHAR (MAX) NULL,
    [Name]           NVARCHAR (MAX) NULL,
    [Password]       NVARCHAR (MAX) NULL,
    [UserName]       NVARCHAR (MAX) NULL,
    [UserType]       INT            NOT NULL,
    [BrokerageId]    NVARCHAR (MAX) NULL,
    [Address]        NVARCHAR (MAX) NULL,
    [Address2]       NVARCHAR (MAX) NULL,
    [MobileNo]       NVARCHAR (MAX) NULL,
    [HomeNo]         NVARCHAR (MAX) NULL,
    [ReferenceBy]    NVARCHAR (MAX) NULL,
    [DateOfBirth]    DATETIME2 (7)  NOT NULL,
    [AadharCardNo]   NVARCHAR (MAX) NULL,
    [DepartmentName] NVARCHAR (MAX) NULL,
    [Designation]    NVARCHAR (MAX) NULL,
    [DateOfJoin]     DATETIME2 (7)  NOT NULL,
    [DateOfEnd]      DATETIME2 (7)  NOT NULL,
    [IsActive]       BIT            NOT NULL,
    [BankName]       NVARCHAR (MAX) NULL,
    [AccountNo]      NVARCHAR (MAX) NULL,
    [IFSCCode]       NVARCHAR (MAX) NULL,
    [IsDelete]       BIT            NOT NULL,
    [CreatedDate]    DATETIME2 (7)  NOT NULL,
    [UpdatedDate]    DATETIME2 (7)  NULL,
    [CreatedBy]      NVARCHAR (MAX) NULL,
    [UpdatedBy]      NVARCHAR (MAX) NULL,
    [BranchMasterId] NVARCHAR (450) NULL,
    CONSTRAINT [PK_UserMaster] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_UserMaster_BranchMaster_BranchMasterId] FOREIGN KEY ([BranchMasterId]) REFERENCES [dbo].[BranchMaster] ([Id])
);

